- Fix for "Transaction check error" at "bitbake meta-toolchain-qt5" build:
Error: Transaction check error:
  file /opt/fslc-framebuffer/2.3.2/sysroots/x86_64-fslcsdk-linux/environment-setup.d conflicts between attempted installs of nativesdk-cmake-3.7.2-r0.x86_64_nativesdk and nativesdk-qtbase-tools-5.9.4+git0+0d9208cecb-r0.x86_64_nativesdk